Add/GitHub actions
10up/restricted-media-poc pull request #17
Opened 2021-01-14 07:36 UTC by jeffpaul

### Description of the Change

Adds linting action, action to deploy new releases to WP.org, and action to deploy changes to readme.txt and/or assets to WP.org.

### Alternate Designs

n/a

### Benefits

automates plugin management tasks

### Possible Drawbacks

Readme/asset changes only to `trunk` or doing a release will trigger the deploy actions, but both should fail with no match on the WP.org SVN side (for now).

### Verification Process

Waiting for PR to run thru checks to see what needs to be fixed before this can be merged.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

n/a

### Changelog Entry

```
### Added
- GitHub Actions (props @jeffpaul)
```

2021-02-06 06:29 UTC, dinhtungdu requested changes
Linting actions are failing, we need to update the composer lock file and specify the JS folder.

2021-02-06 06:29 UTC, dinhtungdu commented on .github/workflows/lint.yml
> +      uses: icrawl/action-eslint@v1
```suggestion
      uses: icrawl/action-eslint@v1
      with:
        custom-glob: assets/js
```

2021-03-04 15:47 UTC, dinhtungdu submitted a review, later dismissed
The PHPCS job is failing due to the outdated `composer.lock` file, @jeffpaul can you please update it? After that, this is ready to be merged

2021-03-05 18:23 UTC, jeffpaul commented
@dinhtungdu looks correct now, minus some actual PHPCS errors, yeah?

2021-03-05 18:43 UTC, jeffpaul commented
Looks like those errors are all docs related, so I'm good merging this on and adding those in a subsequent PR.

2021-03-05 18:43 UTC, merged